name: CommandItems
version: '1.1.0'
main: niix.dan.commanditem.CommandItem
api-version: '1.13'
load: STARTUP
authors: [Niix-Dan]
website: https://github.com/Niix-Dan
commands:
  commanditem:
    usage: /commanditem [reload,set]
    permission: CommandItem.cmdi
    aliases: ["cmdi"]
permissions:
  CommandItem.cmdi:
    default: op